"""Generated by scripts/generate_shared_contracts.py; do not edit."""

from datetime import datetime
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


def _camel(value: str) -> str:
    head, *tail = value.split("_")
    return head + "".join(item.title() for item in tail)


class ContractModel(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True, alias_generator=_camel)

class Role(StrEnum):
    CONFIGURATION_ADMINISTRATOR = "configuration_administrator"
    NGO_PREPARER = "ngo_preparer"
    NGO_APPROVER = "ngo_approver"
    GOVERNMENT_REVIEWER = "government_reviewer"
    AUDITOR = "auditor"

class ResourceKind(StrEnum):
    CONFIGURATION = "configuration"
    INVOICE = "invoice"
    ARTIFACT = "artifact"
    JOB = "job"
    PACKAGE = "package"
    GOVERNMENT_DECISION = "government_decision"
    AUDIT = "audit"

class Action(StrEnum):
    READ = "read"
    CREATE = "create"
    UPDATE = "update"
    ACTIVATE = "activate"
    ATTEST = "attest"
    SUBMIT = "submit"
    RETURN = "return"
    APPROVE = "approve"

class ArtifactKind(StrEnum):
    ORIGINAL = "original"
    GENERATED = "generated"

class FieldType(StrEnum):
    STRING = "string"
    DECIMAL = "decimal"
    INTEGER = "integer"
    BOOLEAN = "boolean"
    DATE = "date"
    DATETIME = "datetime"
    IDENTIFIER = "identifier"
    REFERENCE = "reference"

class EntityType(StrEnum):
    CONTRACT = "contract"
    ARTIFACT = "artifact"
    EXPENSE = "expense"
    INVOICE = "invoice"
    INVOICE_LINE = "invoice_line"
    VALIDATION_RUN = "validation_run"
    PACKAGE = "package"
    SUBMISSION = "submission"
    DECISION = "decision"

class RelationType(StrEnum):
    SUPPORTS = "supports"
    DERIVED_FROM = "derived_from"
    MAPS_TO = "maps_to"
    VALIDATED_BY = "validated_by"
    SUBMITTED_AS = "submitted_as"
    RETURNED_AS = "returned_as"
    AMENDS = "amends"
    APPROVED_AS = "approved_as"

class InvoiceLifecycle(StrEnum):
    DRAFT = "draft"
    SUBMITTED = "submitted"
    RETURNED = "returned"
    APPROVED = "approved"

class ConfigurationLifecycle(StrEnum):
    DRAFT = "draft"
    TESTED = "tested"
    APPROVED = "approved"
    ACTIVE = "active"
    SUPERSEDED = "superseded"
    RETIRED = "retired"

class RuleSeverity(StrEnum):
    BLOCKER = "blocker"
    WARNING = "warning"
    NOTE = "note"

class RuleOutcome(StrEnum):
    PASS = "pass"
    FAIL = "fail"
    NOT_APPLICABLE = "not_applicable"

class EventType(StrEnum):
    LOGIN_SUCCEEDED = "login_succeeded"
    LOGIN_FAILED = "login_failed"
    LOGOUT = "logout"
    CONFIG_ACTIVATED = "config_activated"
    ARTIFACT_UPLOADED = "artifact_uploaded"
    EXTRACTION_DRAFTED = "extraction_drafted"
    EXTRACTION_FAILED = "extraction_failed"
    FIELD_CORRECTED = "field_corrected"
    FIELD_REVIEWED = "field_reviewed"
    VALIDATION_COMPLETED = "validation_completed"
    INVOICE_LINE_CORRECTED = "invoice_line_corrected"
    FINDING_RESOLVED = "finding_resolved"
    ATTESTED = "attested"
    PACKAGE_GENERATED = "package_generated"
    SUBMITTED = "submitted"
    RETURNED = "returned"
    REVISION_CREATED = "revision_created"
    RESUBMITTED = "resubmitted"
    APPROVED = "approved"

MATERIAL_EVENT_TYPES = frozenset(item.value for item in EventType)


class VersionReference(ContractModel):
    kind: str
    id: str
    version: int | str
    sha256: str | None = Field(default=None, pattern=r"^[a-f0-9]{64}$")


class ActorReference(ContractModel):
    user_id: str
    organization_id: str
    role: Role


class ArtifactContract(ContractModel):
    id: str
    contract_id: str
    organization_id: str
    kind: ArtifactKind
    media_type: str
    byte_size: int = Field(ge=0)
    sha256: str = Field(pattern=r"^[a-f0-9]{64}$")
    version: int = Field(ge=1)
    submitted: bool = False


class TypedField(ContractModel):
    name: str
    field_type: FieldType
    value: Any
    source: VersionReference
    confidence: float | None = Field(default=None, ge=0, le=1)


class EntityContract(ContractModel):
    id: str
    entity_type: EntityType
    version: int = Field(ge=1)
    fields: list[TypedField]


class RelationContract(ContractModel):
    id: str
    relation_type: RelationType
    source: VersionReference
    target: VersionReference
    actor: ActorReference | None = None
    reason_code: str | None = None


class RuleDefinition(ContractModel):
    code: str
    version: str
    severity: RuleSeverity
    enabled: bool
    parameters: dict[str, Any]


class RuleResult(ContractModel):
    rule_code: str
    rule_version: str
    severity: RuleSeverity
    reason_code: str
    outcome: RuleOutcome
    normalized_input: dict[str, Any]
    message: str
    expense_key: str | None = None
    remediation: str | None = None


class ValidationRunContract(ContractModel):
    id: str
    invoice_version: VersionReference
    configuration_version: VersionReference
    engine_version: str
    input_hash: str = Field(pattern=r"^[a-f0-9]{64}$")
    output_hash: str = Field(pattern=r"^[a-f0-9]{64}$")
    results: list[RuleResult]


class WorkflowContract(ContractModel):
    id: str
    version: int = Field(ge=1)
    states: list[str]
    transitions: list[dict[str, Any]]


class ViewContract(ContractModel):
    id: str
    version: int = Field(ge=1)
    role: Role
    fields: list[str]


class TemplateContract(ContractModel):
    id: str
    version: int = Field(ge=1)
    media_type: str
    content_hash: str = Field(pattern=r"^[a-f0-9]{64}$")


class EventEnvelope(ContractModel):
    event_id: str
    event_type: EventType
    schema_version: int = Field(ge=1)
    actor: ActorReference
    organization_id: str
    contract_id: str
    aggregate: VersionReference
    occurred_at: datetime
    payload: dict[str, Any]
    version_references: list[VersionReference]
    reason_code: str | None = None


class ConfigurationBundleContract(ContractModel):
    id: str
    version: int = Field(ge=1)
    lifecycle: ConfigurationLifecycle
    scope: dict[str, str]
    schemas: list[VersionReference]
    mappings: list[VersionReference]
    rules: list[RuleDefinition]
    workflow: WorkflowContract
    views: list[ViewContract]
    templates: list[TemplateContract]
    test_evidence: VersionReference | None = None
    approval: ActorReference | None = None
    predecessor: VersionReference | None = None
    rollback_target: VersionReference | None = None


class IdentityDto(ContractModel):
    id: str
    display_name: str
    email: str
    organization_id: str
    organization_name: str
    role: Role


class ActiveConfigurationDto(ContractModel):
    id: str
    version: int
    activated_at: str
