"""Generate Python and TypeScript contracts from canonical typed registries."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Iterator

ROOT = Path(__file__).resolve().parents[1]
SOURCES = {
    "domain": ROOT / "packages/domain-types/contract.json",
    "rules": ROOT / "packages/rule-contracts/contract.json",
    "configuration": ROOT / "packages/configuration-contracts/contract.json",
    "events": ROOT / "packages/event-contracts/contract.json",
}
PYTHON_OUTPUT = ROOT / "services/api-workflow/app/domain/shared_contracts.py"
TYPESCRIPT_OUTPUT = ROOT / "apps/web-app/src/generated/contracts.ts"

PYTHON_PRIMITIVES = {
    "string": "str",
    "integer": "int",
    "number": "float",
    "boolean": "bool",
    "any": "Any",
    "datetime": "datetime",
}
TYPESCRIPT_PRIMITIVES = {
    "string": "string",
    "integer": "number",
    "number": "number",
    "boolean": "boolean",
    "any": "unknown",
    "datetime": "string",
}


def load() -> dict[str, dict]:
    return {name: json.loads(path.read_text()) for name, path in SOURCES.items()}


def member(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9]+", "_", value).strip("_").upper()


def snake(value: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", value).lower()


def vocabulary_definitions(registry: dict[str, dict]) -> Iterator[tuple[str, dict]]:
    for package in registry.values():
        for name, definition in package.get("vocabularies", {}).items():
            yield name, definition


def contract_definitions(registry: dict[str, dict]) -> Iterator[tuple[str, dict]]:
    for package in registry.values():
        yield from package.get("contracts", {}).items()


def python_enum(name: str, values: list[str]) -> str:
    rows = "\n".join(f'    {member(value)} = "{value}"' for value in values)
    return f"class {name}(StrEnum):\n{rows}"


def python_type(type_name: str) -> str:
    if type_name.endswith("[]"):
        return f"list[{python_type(type_name[:-2])}]"
    if type_name.startswith("map<string,") and type_name.endswith(">"):
        return f"dict[str, {python_type(type_name[11:-1])}]"
    if "|" in type_name:
        return " | ".join(python_type(part) for part in type_name.split("|"))
    return PYTHON_PRIMITIVES.get(type_name, type_name)


def typescript_type(type_name: str, aliases: dict[str, str] | None = None) -> str:
    aliases = aliases or {}
    if type_name.endswith("[]"):
        item = typescript_type(type_name[:-2], aliases)
        return f"Array<{item}>" if " | " in item else f"{item}[]"
    if type_name.startswith("map<string,") and type_name.endswith(">"):
        return f"Record<string, {typescript_type(type_name[11:-1], aliases)}>"
    if "|" in type_name:
        return " | ".join(typescript_type(part, aliases) for part in type_name.split("|"))
    return TYPESCRIPT_PRIMITIVES.get(type_name, aliases.get(type_name, type_name))


def python_default(value: object) -> str:
    if value is True:
        return "True"
    if value is False:
        return "False"
    if value is None:
        return "None"
    return repr(value)


def python_field(field: dict) -> str:
    required = field["required"]
    nullable = field.get("nullable", False)
    has_default = "default" in field
    field_type = python_type(field["type"])
    if nullable or (not required and not has_default):
        field_type += " | None"

    constraints: list[str] = []
    if "pattern" in field:
        constraints.append(f"pattern={field['pattern']!r}")
    if "minimum" in field:
        constraints.append(f"ge={field['minimum']!r}")
    if "maximum" in field:
        constraints.append(f"le={field['maximum']!r}")

    if constraints:
        if has_default:
            constraints.insert(0, f"default={python_default(field['default'])}")
        elif not required:
            constraints.insert(0, "default=None")
        assignment = f" = Field({', '.join(constraints)})"
    elif has_default:
        assignment = f" = {python_default(field['default'])}"
    elif not required:
        assignment = " = None"
    else:
        assignment = ""
    return f"    {snake(field['name'])}: {field_type}{assignment}"


def typescript_field(field: dict, aliases: dict[str, str] | None = None) -> str:
    optional = "" if field["required"] else "?"
    field_type = typescript_type(field["type"], aliases)
    if field.get("nullable", False):
        field_type += " | null"
    return f"  {field['name']}{optional}: {field_type};"


def render_python(registry: dict[str, dict]) -> str:
    header = '''"""Generated by scripts/generate_shared_contracts.py; do not edit."""

from datetime import datetime
from enum import StrEnum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, StringConstraints


def _camel(value: str) -> str:
    head, *tail = value.split("_")
    return head + "".join(item.title() for item in tail)


class ContractModel(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True, alias_generator=_camel)
'''
    enums = []
    for _, definition in vocabulary_definitions(registry):
        if not definition.get("python"):
            continue
        if definition.get("parameterized"):
            choices = "|".join(re.escape(value) for value in definition["values"])
            enums.append(
                f"{definition['python']} = Annotated[str, StringConstraints("
                f"pattern=r'^(?:{choices})(?::[A-Za-z0-9_.-]+)*$')]"
            )
        else:
            enums.append(python_enum(definition["python"], definition["values"]))
    models = []
    required_shapes = {}
    for _, definition in contract_definitions(registry):
        fields = "\n".join(python_field(field) for field in definition["fields"])
        models.append(f"class {definition['model']}(ContractModel):\n{fields}")
        required_shapes[definition["model"]] = [
            snake(field["name"]) for field in definition["fields"] if field["required"]
        ]
    required_metadata = "CONTRACT_REQUIRED_FIELDS = {\n" + "\n".join(
        f"    {model!r}: frozenset({fields!r})," for model, fields in required_shapes.items()
    ) + "\n}"
    return (
        header
        + "\n\n\n"
        + "\n\n\n".join(enums)
        + "\n\n\nMATERIAL_EVENT_TYPES = frozenset(item.value for item in EventType)\n\n\n"
        + required_metadata
        + "\n\n\n"
        + "\n\n\n".join(models)
        + "\n"
    )


def render_typescript(registry: dict[str, dict]) -> str:
    constants = []
    aliases = []
    for _, definition in vocabulary_definitions(registry):
        if not definition.get("typescript"):
            continue
        values = json.dumps(definition["values"], separators=(",", ":"))
        constants.append(f"export const {definition['constant']} = {values} as const;")
        if definition.get("parameterized"):
            aliases.append(
                f"export type {definition['typescript']}Base = typeof "
                f"{definition['constant']}[number];\n"
                f"export type {definition['typescript']} = "
                f"{definition['typescript']}Base | `${{{definition['typescript']}Base}}:${{string}}`;"
            )
        else:
            aliases.append(
                f"export type {definition['typescript']} = typeof {definition['constant']}[number];"
            )
    type_aliases = {
        definition["python"]: definition["typescript"]
        for _, definition in vocabulary_definitions(registry)
        if definition.get("python") and definition.get("typescript")
    }
    interfaces = []
    required_shapes = {}
    for _, definition in contract_definitions(registry):
        fields = "\n".join(
            typescript_field(field, type_aliases) for field in definition["fields"]
        )
        interfaces.append(f"export interface {definition['model']} {{\n{fields}\n}}")
        required_shapes[definition["model"]] = [
            field["name"] for field in definition["fields"] if field["required"]
        ]
    required_metadata = (
        "export const CONTRACT_REQUIRED_FIELDS = "
        + json.dumps(required_shapes, separators=(",", ":"))
        + " as const;"
    )
    return (
        "// Generated by scripts/generate_shared_contracts.py; do not edit.\n\n"
        + "\n".join(constants)
        + "\n\n"
        + "\n".join(aliases)
        + "\n\n"
        + required_metadata
        + "\n\n"
        + "\n\n".join(interfaces)
        + "\n"
    )


def outputs() -> dict[Path, str]:
    registry = load()
    return {PYTHON_OUTPUT: render_python(registry), TYPESCRIPT_OUTPUT: render_typescript(registry)}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        print("Generated contracts are stale: " + ", ".join(stale))
        return 1
    if args.check:
        print("Shared contract generation check passed (4 registries, 2 consumers).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
