"""Generated by scripts/generate_shared_contracts.py; do not edit."""

from datetime import datetime
from enum import StrEnum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, StringConstraints


def _camel(value: str) -> str:
    head, *tail = value.split("_")
    return head + "".join(item.title() for item in tail)


class ContractModel(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True, alias_generator=_camel)



class Role(StrEnum):
    CONFIGURATION_ADMINISTRATOR = "configuration_administrator"
    NGO_PREPARER = "ngo_preparer"
    NGO_APPROVER = "ngo_approver"
    GOVERNMENT_REVIEWER = "government_reviewer"
    AUDITOR = "auditor"


class ResourceKind(StrEnum):
    CONFIGURATION = "configuration"
    INVOICE = "invoice"
    ARTIFACT = "artifact"
    JOB = "job"
    PACKAGE = "package"
    GOVERNMENT_DECISION = "government_decision"
    AUDIT = "audit"


class Action(StrEnum):
    READ = "read"
    CREATE = "create"
    UPDATE = "update"
    TEST = "test"
    APPROVE_CONFIGURATION = "approve_configuration"
    ACTIVATE = "activate"
    SUPERSEDE = "supersede"
    RETIRE = "retire"
    ROLLBACK = "rollback"
    ATTEST = "attest"
    SUBMIT = "submit"
    RETURN = "return"
    APPROVE = "approve"


class ArtifactKind(StrEnum):
    ORIGINAL = "original"
    GENERATED = "generated"


class FieldType(StrEnum):
    STRING = "string"
    DECIMAL = "decimal"
    INTEGER = "integer"
    BOOLEAN = "boolean"
    DATE = "date"
    DATETIME = "datetime"
    IDENTIFIER = "identifier"
    REFERENCE = "reference"


class EntityType(StrEnum):
    CONTRACT = "contract"
    ARTIFACT = "artifact"
    EXPENSE = "expense"
    INVOICE = "invoice"
    INVOICE_LINE = "invoice_line"
    VALIDATION_RUN = "validation_run"
    PACKAGE = "package"
    SUBMISSION = "submission"
    DECISION = "decision"


class RelationType(StrEnum):
    SUPPORTS = "supports"
    DERIVED_FROM = "derived_from"
    MAPS_TO = "maps_to"
    VALIDATED_BY = "validated_by"
    SUBMITTED_AS = "submitted_as"
    RETURNED_AS = "returned_as"
    AMENDS = "amends"
    APPROVED_AS = "approved_as"


class InvoiceLifecycle(StrEnum):
    DRAFT = "draft"
    SUBMITTED = "submitted"
    RETURNED = "returned"
    APPROVED = "approved"


class ConfigurationLifecycle(StrEnum):
    DRAFT = "draft"
    TESTED = "tested"
    APPROVED = "approved"
    ACTIVE = "active"
    SUPERSEDED = "superseded"
    RETIRED = "retired"


class DocumentRouteOutcome(StrEnum):
    RECOGNIZED_PROFILE_DRAFT = "recognized_profile_draft"
    NEEDS_PROFILE_REVIEW = "needs_profile_review"
    EXTRACTION_FAILED = "extraction_failed"


ReasonCode = Annotated[str, StringConstraints(pattern=r'^(?:SERVICE_PERIOD|IN_SERVICE_PERIOD|REQUIRED_EVIDENCE|EVIDENCE_PRESENT|BUDGET_AVAILABLE|TOTAL_RECONCILIATION|TOTAL_RECONCILED|POSSIBLE_DUPLICATE|NO_POSSIBLE_DUPLICATE|EVIDENCE_CORRECTION|AMOUNT_CORRECTION|CLARIFICATION|APPROVED_AS_CORRECTED)(?::[A-Za-z0-9_.-]+)*$')]


class VersionReferenceKind(StrEnum):
    CONTRACT = "contract"
    ARTIFACT = "artifact"
    SCHEMA = "schema"
    MAPPING = "mapping"
    RULE = "rule"
    WORKFLOW = "workflow"
    VIEW = "view"
    TEMPLATE = "template"
    CONFIGURATION = "configuration"
    TEST_EVIDENCE = "test_evidence"
    DOCUMENT_PROFILE = "document_profile"
    PROFILE_FIXTURE_SET = "profile_fixture_set"
    PROFILE_EVALUATION = "profile_evaluation"
    DOCUMENT_FINGERPRINT = "document_fingerprint"
    CLUSTER_PROJECTION = "cluster_projection"
    EXTRACTION_RUN = "extraction_run"
    INVOICE = "invoice"
    INVOICE_SNAPSHOT = "invoice_snapshot"
    VALIDATION_RUN = "validation_run"
    PACKAGE = "package"
    PACKAGE_MANIFEST = "package_manifest"
    EVENT = "event"
    ENTITY = "entity"
    SUBMISSION = "submission"
    DECISION = "decision"


class RuleSeverity(StrEnum):
    BLOCKER = "blocker"
    WARNING = "warning"
    NOTE = "note"


class RuleOutcome(StrEnum):
    PASS = "pass"
    FAIL = "fail"
    NOT_APPLICABLE = "not_applicable"


class RuleCode(StrEnum):
    SERVICE_PERIOD = "SERVICE_PERIOD"
    REQUIRED_EVIDENCE = "REQUIRED_EVIDENCE"
    BUDGET_AVAILABLE = "BUDGET_AVAILABLE"
    TOTAL_RECONCILIATION = "TOTAL_RECONCILIATION"
    POSSIBLE_DUPLICATE = "POSSIBLE_DUPLICATE"


class ComponentKind(StrEnum):
    SCHEMA = "schema"
    MAPPING = "mapping"
    RULE = "rule"
    WORKFLOW = "workflow"
    VIEW = "view"
    TEMPLATE = "template"
    DOCUMENT_PROFILE = "document_profile"


class ProfileFixtureCaseKind(StrEnum):
    SUPPORTED_LAYOUT = "supported_layout"
    CHANGED_LAYOUT = "changed_layout"
    UNKNOWN_LAYOUT = "unknown_layout"


class ProfileMatchKind(StrEnum):
    EXACT = "exact"
    NONE = "none"


class LedgerMatchOutcome(StrEnum):
    MATCHED = "matched"
    UNMATCHED = "unmatched"
    AMBIGUOUS = "ambiguous"
    NOT_EVALUATED = "not_evaluated"


class ClusterSuggestionStatus(StrEnum):
    SUGGESTED = "suggested"
    CONFIRMED_AS_DRAFT = "confirmed_as_draft"


class EventType(StrEnum):
    LOGIN_SUCCEEDED = "login_succeeded"
    LOGIN_FAILED = "login_failed"
    LOGOUT = "logout"
    CONFIG_TESTED = "config_tested"
    CONFIG_APPROVED = "config_approved"
    CONFIG_ACTIVATED = "config_activated"
    CONFIG_SUPERSEDED = "config_superseded"
    CONFIG_RETIRED = "config_retired"
    CONFIG_ROLLBACK_PREPARED = "config_rollback_prepared"
    PROFILE_DRAFTED = "profile_drafted"
    PROFILE_TESTED = "profile_tested"
    PROFILE_APPROVED = "profile_approved"
    PROFILE_ACTIVATED = "profile_activated"
    PROFILE_ROLLBACK_ACTIVATED = "profile_rollback_activated"
    PROFILE_SUPERSEDED = "profile_superseded"
    PROFILE_RETIRED = "profile_retired"
    CLUSTER_CONFIRMED = "cluster_confirmed"
    ARTIFACT_UPLOADED = "artifact_uploaded"
    DOCUMENT_ROUTED = "document_routed"
    EXTRACTION_DRAFTED = "extraction_drafted"
    EXTRACTION_FAILED = "extraction_failed"
    FIELD_CORRECTED = "field_corrected"
    FIELD_REVIEWED = "field_reviewed"
    VALIDATION_COMPLETED = "validation_completed"
    INVOICE_LINE_CORRECTED = "invoice_line_corrected"
    FINDING_RESOLVED = "finding_resolved"
    ATTESTED = "attested"
    PACKAGE_GENERATED = "package_generated"
    SUBMITTED = "submitted"
    RETURNED = "returned"
    REVISION_CREATED = "revision_created"
    RESUBMITTED = "resubmitted"
    APPROVED = "approved"


MATERIAL_EVENT_TYPES = frozenset(item.value for item in EventType)


CONTRACT_REQUIRED_FIELDS = {
    'VersionReference': frozenset(['kind', 'id', 'version']),
    'ActorReference': frozenset(['user_id', 'organization_id', 'role']),
    'ArtifactContract': frozenset(['id', 'contract_id', 'organization_id', 'kind', 'media_type', 'byte_size', 'sha256', 'version']),
    'TypedField': frozenset(['name', 'field_type', 'value', 'source']),
    'EntityContract': frozenset(['id', 'entity_type', 'version', 'fields']),
    'RelationContract': frozenset(['id', 'relation_type', 'source', 'target']),
    'IdentityDto': frozenset(['id', 'display_name', 'email', 'organization_id', 'organization_name', 'role']),
    'ContractContextDto': frozenset(['contract_id', 'contract_name', 'agency_organization_id', 'agency_organization_name', 'ngo_organization_id', 'ngo_organization_name']),
    'RuleDefinition': frozenset(['code', 'version', 'severity', 'enabled', 'parameters']),
    'RuleResult': frozenset(['rule_code', 'rule_version', 'severity', 'reason_code', 'outcome', 'normalized_input', 'message']),
    'ValidationRunContract': frozenset(['id', 'invoice_version', 'configuration_version', 'engine_version', 'input_hash', 'output_hash', 'results']),
    'ValidationRunDto': frozenset(['id', 'invoice_version_id', 'configuration_version_id', 'engine_version', 'normalized_inputs', 'input_hash', 'output_hash', 'status', 'results']),
    'WorkflowTransition': frozenset(['from_state', 'to_state', 'action', 'role']),
    'WorkflowContract': frozenset(['id', 'version', 'states', 'transitions']),
    'ViewContract': frozenset(['id', 'version', 'role', 'fields']),
    'TemplateContract': frozenset(['id', 'version', 'media_type', 'content_hash']),
    'ExtractionComponentVersionContract': frozenset(['source_artifact', 'provider', 'model', 'prompt_version', 'parser_version', 'schema_version']),
    'ValidationInputManifestContract': frozenset(['schema_version', 'engine_version', 'normalized_inputs', 'invoice_snapshot', 'artifacts', 'schemas', 'mappings', 'rules', 'workflow', 'views', 'templates', 'configuration_version', 'extraction_components']),
    'PackageFileDigestContract': frozenset(['path', 'sha256', 'byte_size']),
    'PackageBuildInputContract': frozenset(['schema_version', 'package_id', 'invoice_snapshot', 'attestation_id', 'validation_run', 'validation_input_manifest_id', 'validation_input_manifest_hash', 'configuration_version', 'template', 'invoice_payload', 'validation_summary', 'claims', 'evidence']),
    'PackageReproductionManifestContract': frozenset(['schema_version', 'build_input_hash', 'package_manifest_hash', 'archive_sha256', 'archive_byte_size', 'files', 'template', 'validation_input_manifest_id', 'validation_input_manifest_hash', 'invoice_snapshot']),
    'ConfigurationBundleContract': frozenset(['id', 'version', 'lifecycle', 'scope', 'schemas', 'mappings', 'rules', 'workflow', 'views', 'templates']),
    'DocumentProfileFieldContract': frozenset(['name', 'field_type', 'required', 'source_labels', 'normalization']),
    'LedgerMatchRuleContract': frozenset(['source_reference_field', 'amount_field', 'date_field', 'vendor_field', 'required']),
    'FingerprintSpecificationContract': frozenset(['id', 'version', 'algorithm', 'signals']),
    'ProfileFixtureCaseContract': frozenset(['id', 'case_kind', 'filename', 'media_type', 'ocr_text', 'expected_outcome', 'expected_fields', 'expected_source_locations']),
    'ProfileFixtureSetContract': frozenset(['id', 'version', 'cases', 'content_hash']),
    'ProfileEvaluationResultContract': frozenset(['fixture_id', 'passed', 'outcome', 'fingerprint', 'normalized_fields_hash', 'source_locations_hash']),
    'ProfileEvaluationEvidenceContract': frozenset(['id', 'profile_version', 'fixture_set', 'suite_version', 'ocr_version', 'parser_version', 'results', 'supported_field_exactness', 'source_location_exactness', 'unknown_safe_routing_rate', 'passed', 'result_hash']),
    'DocumentProfileVersionContract': frozenset(['id', 'contract_id', 'profile_key', 'version', 'lifecycle', 'artifact_class', 'language_tag', 'vendor_aliases', 'required_fields', 'ledger_match_rule', 'fingerprint_specification', 'accepted_fingerprints', 'fixture_set', 'evaluation_evidence', 'content_hash']),
    'ProfileAssociationDto': frozenset(['id', 'contract_id', 'cluster_projection', 'profile_key', 'status', 'confirmed_by', 'rationale', 'created_at']),
    'ConfigurationLifecycleEventDto': frozenset(['state', 'action', 'actor_id', 'actor_role', 'actor_organization_id', 'rationale', 'test_evidence_id', 'approval_id', 'predecessor_version_id', 'successor_version_id', 'rollback_target_version_id', 'event_hash', 'occurred_at']),
    'ConfigurationDraftDto': frozenset(['configuration', 'revision', 'payload_hash', 'updated_at']),
    'ConfigurationTestCheckDto': frozenset(['code', 'passed']),
    'ConfigurationTestEvidenceDto': frozenset(['id', 'suite_version', 'payload_hash', 'result_hash', 'passed', 'checks', 'tested_by', 'tested_role', 'tested_organization_id', 'rationale', 'created_at']),
    'ConfigurationApprovalEvidenceDto': frozenset(['id', 'test_evidence_id', 'approved_by', 'approved_role', 'approved_organization_id', 'rationale', 'approval_hash', 'approved_at']),
    'GovernedConfigurationVersionDto': frozenset(['id', 'contract_id', 'version', 'configuration', 'state', 'active', 'payload_hash', 'test_evidence', 'approval', 'history']),
    'ConfigurationLifecycleResponseDto': frozenset(['versions']),
    'ConfigurationDiffChangeDto': frozenset(['path', 'change_type', 'before', 'after', 'description']),
    'ConfigurationDiffDto': frozenset(['contract_id', 'base_version_id', 'target_version_id', 'changes', 'projection_hash', 'canonical']),
    'ConfigurationReferenceDto': frozenset(['resource_kind', 'resource_id', 'resource_version', 'state', 'recorded_at']),
    'ConfigurationReferencesDto': frozenset(['configuration_version_id', 'references', 'projection_hash', 'canonical']),
    'ConfigurationActivationImpactDto': frozenset(['configuration_version_id', 'contract_id', 'would_supersede_version_id', 'historical_reference_version_id', 'reference_counts', 'application_scope', 'historical_references_preserved', 'projection_hash', 'canonical']),
    'ActiveConfigurationDto': frozenset(['id', 'version', 'activated_at']),
    'SourceLocationContract': frozenset(['page', 'line', 'label', 'canonical']),
    'ExtractedFieldProposalContract': frozenset(['name', 'field_type', 'value', 'source_location', 'confidence']),
    'DocumentFingerprintContract': frozenset(['id', 'artifact', 'specification_version', 'algorithm', 'language_tag', 'signals', 'sha256']),
    'DocumentClusterProjectionContract': frozenset(['id', 'contract_id', 'fingerprint', 'language_tag', 'member_artifacts', 'status', 'canonical', 'projection_hash']),
    'ProfileMatchResultContract': frozenset(['id', 'outcome', 'match_kind', 'profile_version', 'configuration_version', 'fingerprint', 'ledger_match_outcome', 'reason', 'result_hash']),
    'DocumentIntakeResultDto': frozenset(['extraction_run_id', 'source_artifact', 'raw_ocr_artifact', 'ocr_version', 'parser_version', 'fingerprint', 'match', 'cluster', 'fields', 'human_review_required']),
    'EventEnvelope': frozenset(['event_id', 'event_type', 'schema_version', 'actor', 'organization_id', 'contract_id', 'aggregate', 'occurred_at', 'payload', 'version_references']),
    'AuditEventDto': frozenset(['id', 'event', 'event_hash']),
    'AuditLineageDto': frozenset(['id', 'field_name', 'field_value', 'recorded_at']),
    'AuditRelationDto': frozenset(['id', 'relation_type', 'source', 'target', 'actor', 'relation_hash', 'created_at']),
    'AuditSnapshotDto': frozenset(['id', 'invoice_version_id', 'invoice_version', 'material_revision', 'stage', 'payload', 'snapshot_hash', 'actor', 'created_at']),
    'AuditPackageDto': frozenset(['package_id', 'invoice_version_id', 'invoice_version', 'reproduction_manifest_id', 'validation_input_manifest_id', 'validation_input_manifest_hash', 'build_input_hash', 'package_manifest_hash', 'archive_sha256', 'reproduction_manifest_hash', 'template_id', 'template_version', 'template_hash', 'manifest', 'build_input']),
    'ClaimedAmountTrailDto': frozenset(['expense_key', 'claimed_amount', 'source_artifact_id', 'source_location', 'validation_run_id', 'invoice_snapshot_id', 'invoice_version_id', 'invoice_version', 'package_id', 'package_manifest_hash', 'archive_sha256']),
    'AuditTimelineDto': frozenset(['contract_id', 'events', 'lineage', 'relations', 'snapshots', 'packages', 'claimed_amount_trails']),
}


class VersionReference(ContractModel):
    kind: VersionReferenceKind
    id: str
    version: int | str
    sha256: str | None = Field(default=None, pattern='^[a-f0-9]{64}$')


class ActorReference(ContractModel):
    user_id: str
    organization_id: str
    role: Role


class ArtifactContract(ContractModel):
    id: str
    contract_id: str
    organization_id: str
    kind: ArtifactKind
    media_type: str
    byte_size: int = Field(ge=0)
    sha256: str = Field(pattern='^[a-f0-9]{64}$')
    version: int = Field(ge=1)
    submitted: bool = False


class TypedField(ContractModel):
    name: str
    field_type: FieldType
    value: Any
    source: VersionReference
    confidence: float | None = Field(default=None, ge=0, le=1)
    source_location: str | None = None


class EntityContract(ContractModel):
    id: str
    entity_type: EntityType
    version: int = Field(ge=1)
    fields: list[TypedField]


class RelationContract(ContractModel):
    id: str
    relation_type: RelationType
    source: VersionReference
    target: VersionReference
    actor: ActorReference | None = None
    reason_code: ReasonCode | None = None


class IdentityDto(ContractModel):
    id: str
    display_name: str
    email: str
    organization_id: str
    organization_name: str
    role: Role


class ContractContextDto(ContractModel):
    contract_id: str
    contract_name: str
    agency_organization_id: str
    agency_organization_name: str
    ngo_organization_id: str
    ngo_organization_name: str


class RuleDefinition(ContractModel):
    code: RuleCode
    version: str
    severity: RuleSeverity
    enabled: bool
    parameters: dict[str, Any]


class RuleResult(ContractModel):
    rule_code: RuleCode
    rule_version: str
    severity: RuleSeverity
    reason_code: ReasonCode
    outcome: RuleOutcome
    normalized_input: dict[str, Any]
    message: str
    expense_key: str | None = None
    remediation: str | None = None


class ValidationRunContract(ContractModel):
    id: str
    invoice_version: VersionReference
    configuration_version: VersionReference
    engine_version: str
    input_hash: str = Field(pattern='^[a-f0-9]{64}$')
    output_hash: str = Field(pattern='^[a-f0-9]{64}$')
    results: list[RuleResult]


class ValidationRunDto(ContractModel):
    id: str
    invoice_version_id: str
    configuration_version_id: str
    engine_version: str
    normalized_inputs: dict[str, Any]
    input_hash: str = Field(pattern='^[a-f0-9]{64}$')
    output_hash: str = Field(pattern='^[a-f0-9]{64}$')
    status: str
    results: list[RuleResult]
    input_manifest_id: str | None = None
    input_manifest_hash: str | None = Field(default=None, pattern='^[a-f0-9]{64}$')


class WorkflowTransition(ContractModel):
    from_state: InvoiceLifecycle
    to_state: InvoiceLifecycle
    action: Action
    role: Role


class WorkflowContract(ContractModel):
    id: str
    version: int = Field(ge=1)
    states: list[InvoiceLifecycle]
    transitions: list[WorkflowTransition]


class ViewContract(ContractModel):
    id: str
    version: int = Field(ge=1)
    role: Role
    fields: list[str]


class TemplateContract(ContractModel):
    id: str
    version: int = Field(ge=1)
    media_type: str
    content_hash: str = Field(pattern='^[a-f0-9]{64}$')
    parameters: dict[str, Any] | None = None


class ExtractionComponentVersionContract(ContractModel):
    source_artifact: VersionReference
    raw_response_artifact: VersionReference | None = None
    provider: str
    model: str
    prompt_version: str
    parser_version: str
    schema_version: str
    document_profile: VersionReference | None = None
    document_fingerprint: VersionReference | None = None
    configuration_version: VersionReference | None = None


class ValidationInputManifestContract(ContractModel):
    schema_version: str
    engine_version: str
    normalized_inputs: dict[str, Any]
    invoice_snapshot: VersionReference
    artifacts: list[VersionReference]
    schemas: list[VersionReference]
    mappings: list[VersionReference]
    rules: list[RuleDefinition]
    workflow: WorkflowContract
    views: list[ViewContract]
    templates: list[TemplateContract]
    configuration_version: VersionReference
    extraction_components: list[ExtractionComponentVersionContract]


class PackageFileDigestContract(ContractModel):
    path: str
    sha256: str = Field(pattern='^[a-f0-9]{64}$')
    byte_size: int = Field(ge=0)


class PackageBuildInputContract(ContractModel):
    schema_version: str
    package_id: str
    invoice_snapshot: VersionReference
    attestation_id: str
    validation_run: VersionReference
    validation_input_manifest_id: str
    validation_input_manifest_hash: str = Field(pattern='^[a-f0-9]{64}$')
    configuration_version: VersionReference
    template: TemplateContract
    invoice_payload: dict[str, Any]
    validation_summary: dict[str, Any]
    claims: list[dict[str, Any]]
    evidence: list[VersionReference]


class PackageReproductionManifestContract(ContractModel):
    schema_version: str
    build_input_hash: str = Field(pattern='^[a-f0-9]{64}$')
    package_manifest_hash: str = Field(pattern='^[a-f0-9]{64}$')
    archive_sha256: str = Field(pattern='^[a-f0-9]{64}$')
    archive_byte_size: int = Field(ge=0)
    files: list[PackageFileDigestContract]
    template: TemplateContract
    validation_input_manifest_id: str
    validation_input_manifest_hash: str = Field(pattern='^[a-f0-9]{64}$')
    invoice_snapshot: VersionReference


class ConfigurationBundleContract(ContractModel):
    id: str
    version: int = Field(ge=1)
    lifecycle: ConfigurationLifecycle
    scope: dict[str, str]
    schemas: list[VersionReference]
    mappings: list[VersionReference]
    rules: list[RuleDefinition]
    workflow: WorkflowContract
    views: list[ViewContract]
    templates: list[TemplateContract]
    test_evidence: VersionReference | None = None
    approval: ActorReference | None = None
    predecessor: VersionReference | None = None
    rollback_target: VersionReference | None = None
    document_profiles: list[VersionReference] | None = None


class DocumentProfileFieldContract(ContractModel):
    name: str
    field_type: FieldType
    required: bool
    source_labels: list[str]
    normalization: str


class LedgerMatchRuleContract(ContractModel):
    source_reference_field: str
    amount_field: str
    date_field: str
    vendor_field: str
    required: bool


class FingerprintSpecificationContract(ContractModel):
    id: str
    version: str
    algorithm: str
    signals: list[str]


class ProfileFixtureCaseContract(ContractModel):
    id: str
    case_kind: ProfileFixtureCaseKind
    filename: str
    media_type: str
    ocr_text: str
    expected_outcome: DocumentRouteOutcome
    expected_fields: dict[str, str]
    expected_source_locations: dict[str, str]


class ProfileFixtureSetContract(ContractModel):
    id: str
    version: str
    cases: list[ProfileFixtureCaseContract]
    content_hash: str = Field(pattern='^[a-f0-9]{64}$')


class ProfileEvaluationResultContract(ContractModel):
    fixture_id: str
    passed: bool
    outcome: str
    fingerprint: str = Field(pattern='^[a-f0-9]{64}$')
    normalized_fields_hash: str = Field(pattern='^[a-f0-9]{64}$')
    source_locations_hash: str = Field(pattern='^[a-f0-9]{64}$')


class ProfileEvaluationEvidenceContract(ContractModel):
    id: str
    profile_version: VersionReference
    fixture_set: VersionReference
    suite_version: str
    ocr_version: str
    parser_version: str
    results: list[ProfileEvaluationResultContract]
    supported_field_exactness: float = Field(ge=0, le=1)
    source_location_exactness: float = Field(ge=0, le=1)
    unknown_safe_routing_rate: float = Field(ge=0, le=1)
    passed: bool
    result_hash: str = Field(pattern='^[a-f0-9]{64}$')


class DocumentProfileVersionContract(ContractModel):
    id: str
    contract_id: str
    profile_key: str
    version: int = Field(ge=1)
    lifecycle: ConfigurationLifecycle
    artifact_class: str
    language_tag: str
    vendor_aliases: list[str]
    required_fields: list[DocumentProfileFieldContract]
    ledger_match_rule: LedgerMatchRuleContract
    fingerprint_specification: FingerprintSpecificationContract
    accepted_fingerprints: list[str]
    fixture_set: VersionReference
    evaluation_evidence: VersionReference | None
    predecessor: VersionReference | None = None
    successor: VersionReference | None = None
    content_hash: str = Field(pattern='^[a-f0-9]{64}$')


class ProfileAssociationDto(ContractModel):
    id: str
    contract_id: str
    cluster_projection: VersionReference
    profile_key: str
    status: str
    confirmed_by: ActorReference
    rationale: str
    created_at: datetime


class ConfigurationLifecycleEventDto(ContractModel):
    state: ConfigurationLifecycle
    action: Action
    actor_id: str
    actor_role: Role
    actor_organization_id: str
    rationale: str
    test_evidence_id: str | None
    approval_id: str | None
    predecessor_version_id: str | None
    successor_version_id: str | None
    rollback_target_version_id: str | None
    event_hash: str = Field(pattern='^[a-f0-9]{64}$')
    occurred_at: datetime


class ConfigurationDraftDto(ContractModel):
    configuration: dict[str, Any]
    revision: int = Field(ge=1)
    payload_hash: str = Field(pattern='^[a-f0-9]{64}$')
    updated_at: datetime


class ConfigurationTestCheckDto(ContractModel):
    code: str
    passed: bool


class ConfigurationTestEvidenceDto(ContractModel):
    id: str
    suite_version: str
    payload_hash: str = Field(pattern='^[a-f0-9]{64}$')
    result_hash: str = Field(pattern='^[a-f0-9]{64}$')
    passed: bool
    checks: list[ConfigurationTestCheckDto]
    tested_by: str
    tested_role: Role
    tested_organization_id: str
    rationale: str
    created_at: datetime


class ConfigurationApprovalEvidenceDto(ContractModel):
    id: str
    test_evidence_id: str
    approved_by: str
    approved_role: Role
    approved_organization_id: str
    rationale: str
    approval_hash: str = Field(pattern='^[a-f0-9]{64}$')
    approved_at: datetime


class GovernedConfigurationVersionDto(ContractModel):
    id: str
    contract_id: str
    version: int = Field(ge=1)
    configuration: dict[str, Any]
    state: ConfigurationLifecycle
    active: bool
    payload_hash: str = Field(pattern='^[a-f0-9]{64}$')
    test_evidence: ConfigurationTestEvidenceDto | None
    approval: ConfigurationApprovalEvidenceDto | None
    history: list[ConfigurationLifecycleEventDto]


class ConfigurationLifecycleResponseDto(ContractModel):
    versions: list[GovernedConfigurationVersionDto]


class ConfigurationDiffChangeDto(ContractModel):
    path: str
    change_type: str
    before: Any | None
    after: Any | None
    description: str


class ConfigurationDiffDto(ContractModel):
    contract_id: str
    base_version_id: str
    target_version_id: str
    changes: list[ConfigurationDiffChangeDto]
    projection_hash: str = Field(pattern='^[a-f0-9]{64}$')
    canonical: bool


class ConfigurationReferenceDto(ContractModel):
    resource_kind: str
    resource_id: str
    resource_version: str
    state: str
    recorded_at: datetime


class ConfigurationReferencesDto(ContractModel):
    configuration_version_id: str
    references: list[ConfigurationReferenceDto]
    projection_hash: str = Field(pattern='^[a-f0-9]{64}$')
    canonical: bool


class ConfigurationActivationImpactDto(ContractModel):
    configuration_version_id: str
    contract_id: str
    would_supersede_version_id: str | None
    historical_reference_version_id: str | None
    reference_counts: dict[str, int]
    application_scope: str
    historical_references_preserved: bool
    projection_hash: str = Field(pattern='^[a-f0-9]{64}$')
    canonical: bool


class ActiveConfigurationDto(ContractModel):
    id: str
    version: int
    activated_at: str
    document_profiles: list[VersionReference] | None = None


class SourceLocationContract(ContractModel):
    page: int = Field(ge=1)
    line: int = Field(ge=1)
    label: str
    canonical: str


class ExtractedFieldProposalContract(ContractModel):
    name: str
    field_type: FieldType
    value: str
    source_location: SourceLocationContract
    confidence: float = Field(ge=0, le=1)


class DocumentFingerprintContract(ContractModel):
    id: str
    artifact: VersionReference
    specification_version: str
    algorithm: str
    language_tag: str
    signals: dict[str, Any]
    sha256: str = Field(pattern='^[a-f0-9]{64}$')


class DocumentClusterProjectionContract(ContractModel):
    id: str
    contract_id: str
    fingerprint: VersionReference
    language_tag: str
    member_artifacts: list[VersionReference]
    status: ClusterSuggestionStatus
    canonical: bool
    projection_hash: str = Field(pattern='^[a-f0-9]{64}$')


class ProfileMatchResultContract(ContractModel):
    id: str
    outcome: DocumentRouteOutcome
    match_kind: ProfileMatchKind
    profile_version: VersionReference | None
    configuration_version: VersionReference | None
    fingerprint: VersionReference
    ledger_match_outcome: LedgerMatchOutcome
    ledger_expense_key: str | None = None
    reason: str
    result_hash: str = Field(pattern='^[a-f0-9]{64}$')


class DocumentIntakeResultDto(ContractModel):
    extraction_run_id: str
    source_artifact: VersionReference
    raw_ocr_artifact: VersionReference
    ocr_version: str
    parser_version: str
    fingerprint: DocumentFingerprintContract
    match: ProfileMatchResultContract
    cluster: DocumentClusterProjectionContract | None
    fields: list[ExtractedFieldProposalContract]
    human_review_required: bool


class EventEnvelope(ContractModel):
    event_id: str
    event_type: EventType
    schema_version: int = Field(ge=1)
    actor: ActorReference
    organization_id: str
    contract_id: str
    aggregate: VersionReference
    occurred_at: datetime
    payload: dict[str, Any]
    version_references: list[VersionReference]
    reason_code: ReasonCode | None = None


class AuditEventDto(ContractModel):
    id: int
    event: EventEnvelope
    event_hash: str = Field(pattern='^[a-f0-9]{64}$')


class AuditLineageDto(ContractModel):
    id: int
    field_name: str
    field_value: Any
    source_artifact_id: str | None = None
    source_location: str | None = None
    importer_version: str | None = None
    extractor_provider: str | None = None
    extractor_model: str | None = None
    prompt_version: str | None = None
    parser_version: str | None = None
    mapping_version: str | None = None
    correction_actor: ActorReference | None = None
    correction_reason: str | None = None
    validation_run_id: str | None = None
    invoice_version_id: str | None = None
    package_artifact_id: str | None = None
    predecessor_lineage_id: int | None = None
    recorded_at: datetime


class AuditRelationDto(ContractModel):
    id: str
    relation_type: RelationType
    source: VersionReference
    target: VersionReference
    actor: ActorReference
    reason_code: ReasonCode | None = None
    relation_hash: str = Field(pattern='^[a-f0-9]{64}$')
    created_at: datetime


class AuditSnapshotDto(ContractModel):
    id: str
    invoice_version_id: str
    invoice_version: int
    material_revision: int
    stage: str
    payload: dict[str, Any]
    snapshot_hash: str = Field(pattern='^[a-f0-9]{64}$')
    actor: ActorReference
    created_at: datetime


class AuditPackageDto(ContractModel):
    package_id: str
    invoice_version_id: str
    invoice_version: int
    reproduction_manifest_id: str
    validation_input_manifest_id: str
    validation_input_manifest_hash: str = Field(pattern='^[a-f0-9]{64}$')
    build_input_hash: str = Field(pattern='^[a-f0-9]{64}$')
    package_manifest_hash: str = Field(pattern='^[a-f0-9]{64}$')
    archive_sha256: str = Field(pattern='^[a-f0-9]{64}$')
    reproduction_manifest_hash: str = Field(pattern='^[a-f0-9]{64}$')
    template_id: str
    template_version: int
    template_hash: str = Field(pattern='^[a-f0-9]{64}$')
    configuration_version: VersionReference | None = None
    document_profiles: list[VersionReference] | None = None
    manifest: dict[str, Any]
    build_input: dict[str, Any]


class ClaimedAmountTrailDto(ContractModel):
    expense_key: str
    claimed_amount: str
    source_artifact_id: str
    source_location: str
    validation_run_id: str
    invoice_snapshot_id: str
    invoice_version_id: str
    invoice_version: int
    package_id: str
    package_manifest_hash: str = Field(pattern='^[a-f0-9]{64}$')
    archive_sha256: str = Field(pattern='^[a-f0-9]{64}$')


class AuditTimelineDto(ContractModel):
    contract_id: str
    events: list[AuditEventDto]
    lineage: list[AuditLineageDto]
    relations: list[AuditRelationDto]
    snapshots: list[AuditSnapshotDto]
    packages: list[AuditPackageDto]
    claimed_amount_trails: list[ClaimedAmountTrailDto]
