"""Generated by scripts/generate_shared_contracts.py; do not edit."""

from datetime import datetime
from enum import StrEnum
from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field, StringConstraints


def _camel(value: str) -> str:
    head, *tail = value.split("_")
    return head + "".join(item.title() for item in tail)


class ContractModel(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True, alias_generator=_camel)



class Role(StrEnum):
    CONFIGURATION_ADMINISTRATOR = "configuration_administrator"
    NGO_PREPARER = "ngo_preparer"
    NGO_APPROVER = "ngo_approver"
    GOVERNMENT_REVIEWER = "government_reviewer"
    AUDITOR = "auditor"


class ResourceKind(StrEnum):
    CONFIGURATION = "configuration"
    INVOICE = "invoice"
    ARTIFACT = "artifact"
    JOB = "job"
    PACKAGE = "package"
    GOVERNMENT_DECISION = "government_decision"
    AUDIT = "audit"


class Action(StrEnum):
    READ = "read"
    CREATE = "create"
    UPDATE = "update"
    TEST = "test"
    APPROVE_CONFIGURATION = "approve_configuration"
    ACTIVATE = "activate"
    SUPERSEDE = "supersede"
    RETIRE = "retire"
    ROLLBACK = "rollback"
    ATTEST = "attest"
    SUBMIT = "submit"
    RETURN = "return"
    APPROVE = "approve"


class ArtifactKind(StrEnum):
    ORIGINAL = "original"
    GENERATED = "generated"


class FieldType(StrEnum):
    STRING = "string"
    DECIMAL = "decimal"
    INTEGER = "integer"
    BOOLEAN = "boolean"
    DATE = "date"
    DATETIME = "datetime"
    IDENTIFIER = "identifier"
    REFERENCE = "reference"


class EntityType(StrEnum):
    CONTRACT = "contract"
    ARTIFACT = "artifact"
    EXPENSE = "expense"
    INVOICE = "invoice"
    INVOICE_LINE = "invoice_line"
    VALIDATION_RUN = "validation_run"
    PACKAGE = "package"
    SUBMISSION = "submission"
    DECISION = "decision"


class RelationType(StrEnum):
    SUPPORTS = "supports"
    DERIVED_FROM = "derived_from"
    MAPS_TO = "maps_to"
    VALIDATED_BY = "validated_by"
    SUBMITTED_AS = "submitted_as"
    RETURNED_AS = "returned_as"
    AMENDS = "amends"
    APPROVED_AS = "approved_as"


class InvoiceLifecycle(StrEnum):
    DRAFT = "draft"
    SUBMITTED = "submitted"
    RETURNED = "returned"
    APPROVED = "approved"


class ConfigurationLifecycle(StrEnum):
    DRAFT = "draft"
    TESTED = "tested"
    APPROVED = "approved"
    ACTIVE = "active"
    SUPERSEDED = "superseded"
    RETIRED = "retired"


ReasonCode = Annotated[str, StringConstraints(pattern=r'^(?:SERVICE_PERIOD|IN_SERVICE_PERIOD|REQUIRED_EVIDENCE|EVIDENCE_PRESENT|BUDGET_AVAILABLE|TOTAL_RECONCILIATION|TOTAL_RECONCILED|POSSIBLE_DUPLICATE|NO_POSSIBLE_DUPLICATE|EVIDENCE_CORRECTION|AMOUNT_CORRECTION|CLARIFICATION|APPROVED_AS_CORRECTED)(?::[A-Za-z0-9_.-]+)*$')]


class VersionReferenceKind(StrEnum):
    CONTRACT = "contract"
    ARTIFACT = "artifact"
    SCHEMA = "schema"
    MAPPING = "mapping"
    RULE = "rule"
    WORKFLOW = "workflow"
    VIEW = "view"
    TEMPLATE = "template"
    CONFIGURATION = "configuration"
    TEST_EVIDENCE = "test_evidence"
    INVOICE = "invoice"
    INVOICE_SNAPSHOT = "invoice_snapshot"
    VALIDATION_RUN = "validation_run"
    PACKAGE = "package"
    PACKAGE_MANIFEST = "package_manifest"
    EVENT = "event"
    ENTITY = "entity"
    SUBMISSION = "submission"
    DECISION = "decision"


class RuleSeverity(StrEnum):
    BLOCKER = "blocker"
    WARNING = "warning"
    NOTE = "note"


class RuleOutcome(StrEnum):
    PASS = "pass"
    FAIL = "fail"
    NOT_APPLICABLE = "not_applicable"


class RuleCode(StrEnum):
    SERVICE_PERIOD = "SERVICE_PERIOD"
    REQUIRED_EVIDENCE = "REQUIRED_EVIDENCE"
    BUDGET_AVAILABLE = "BUDGET_AVAILABLE"
    TOTAL_RECONCILIATION = "TOTAL_RECONCILIATION"
    POSSIBLE_DUPLICATE = "POSSIBLE_DUPLICATE"


class ComponentKind(StrEnum):
    SCHEMA = "schema"
    MAPPING = "mapping"
    RULE = "rule"
    WORKFLOW = "workflow"
    VIEW = "view"
    TEMPLATE = "template"


class EventType(StrEnum):
    LOGIN_SUCCEEDED = "login_succeeded"
    LOGIN_FAILED = "login_failed"
    LOGOUT = "logout"
    CONFIG_TESTED = "config_tested"
    CONFIG_APPROVED = "config_approved"
    CONFIG_ACTIVATED = "config_activated"
    CONFIG_SUPERSEDED = "config_superseded"
    CONFIG_RETIRED = "config_retired"
    CONFIG_ROLLBACK_PREPARED = "config_rollback_prepared"
    ARTIFACT_UPLOADED = "artifact_uploaded"
    EXTRACTION_DRAFTED = "extraction_drafted"
    EXTRACTION_FAILED = "extraction_failed"
    FIELD_CORRECTED = "field_corrected"
    FIELD_REVIEWED = "field_reviewed"
    VALIDATION_COMPLETED = "validation_completed"
    INVOICE_LINE_CORRECTED = "invoice_line_corrected"
    FINDING_RESOLVED = "finding_resolved"
    ATTESTED = "attested"
    PACKAGE_GENERATED = "package_generated"
    SUBMITTED = "submitted"
    RETURNED = "returned"
    REVISION_CREATED = "revision_created"
    RESUBMITTED = "resubmitted"
    APPROVED = "approved"


MATERIAL_EVENT_TYPES = frozenset(item.value for item in EventType)


CONTRACT_REQUIRED_FIELDS = {
    'VersionReference': frozenset(['kind', 'id', 'version']),
    'ActorReference': frozenset(['user_id', 'organization_id', 'role']),
    'ArtifactContract': frozenset(['id', 'contract_id', 'organization_id', 'kind', 'media_type', 'byte_size', 'sha256', 'version']),
    'TypedField': frozenset(['name', 'field_type', 'value', 'source']),
    'EntityContract': frozenset(['id', 'entity_type', 'version', 'fields']),
    'RelationContract': frozenset(['id', 'relation_type', 'source', 'target']),
    'IdentityDto': frozenset(['id', 'display_name', 'email', 'organization_id', 'organization_name', 'role']),
    'ContractContextDto': frozenset(['contract_id', 'contract_name', 'agency_organization_id', 'agency_organization_name', 'ngo_organization_id', 'ngo_organization_name']),
    'RuleDefinition': frozenset(['code', 'version', 'severity', 'enabled', 'parameters']),
    'RuleResult': frozenset(['rule_code', 'rule_version', 'severity', 'reason_code', 'outcome', 'normalized_input', 'message']),
    'ValidationRunContract': frozenset(['id', 'invoice_version', 'configuration_version', 'engine_version', 'input_hash', 'output_hash', 'results']),
    'ValidationRunDto': frozenset(['id', 'invoice_version_id', 'configuration_version_id', 'engine_version', 'normalized_inputs', 'input_hash', 'output_hash', 'status', 'results']),
    'WorkflowTransition': frozenset(['from_state', 'to_state', 'action', 'role']),
    'WorkflowContract': frozenset(['id', 'version', 'states', 'transitions']),
    'ViewContract': frozenset(['id', 'version', 'role', 'fields']),
    'TemplateContract': frozenset(['id', 'version', 'media_type', 'content_hash']),
    'ExtractionComponentVersionContract': frozenset(['source_artifact', 'provider', 'model', 'prompt_version', 'parser_version', 'schema_version']),
    'ValidationInputManifestContract': frozenset(['schema_version', 'engine_version', 'normalized_inputs', 'invoice_snapshot', 'artifacts', 'schemas', 'mappings', 'rules', 'workflow', 'views', 'templates', 'configuration_version', 'extraction_components']),
    'PackageFileDigestContract': frozenset(['path', 'sha256', 'byte_size']),
    'PackageBuildInputContract': frozenset(['schema_version', 'package_id', 'invoice_snapshot', 'attestation_id', 'validation_run', 'validation_input_manifest_id', 'validation_input_manifest_hash', 'configuration_version', 'template', 'invoice_payload', 'validation_summary', 'claims', 'evidence']),
    'PackageReproductionManifestContract': frozenset(['schema_version', 'build_input_hash', 'package_manifest_hash', 'archive_sha256', 'archive_byte_size', 'files', 'template', 'validation_input_manifest_id', 'validation_input_manifest_hash', 'invoice_snapshot']),
    'ConfigurationBundleContract': frozenset(['id', 'version', 'lifecycle', 'scope', 'schemas', 'mappings', 'rules', 'workflow', 'views', 'templates']),
    'ConfigurationLifecycleEventDto': frozenset(['state', 'action', 'actor_id', 'actor_role', 'actor_organization_id', 'rationale', 'test_evidence_id', 'approval_id', 'predecessor_version_id', 'successor_version_id', 'rollback_target_version_id', 'event_hash', 'occurred_at']),
    'GovernedConfigurationVersionDto': frozenset(['id', 'version', 'configuration', 'state', 'active', 'history']),
    'ConfigurationLifecycleResponseDto': frozenset(['versions']),
    'ActiveConfigurationDto': frozenset(['id', 'version', 'activated_at']),
    'EventEnvelope': frozenset(['event_id', 'event_type', 'schema_version', 'actor', 'organization_id', 'contract_id', 'aggregate', 'occurred_at', 'payload', 'version_references']),
}


class VersionReference(ContractModel):
    kind: VersionReferenceKind
    id: str
    version: int | str
    sha256: str | None = Field(default=None, pattern='^[a-f0-9]{64}$')


class ActorReference(ContractModel):
    user_id: str
    organization_id: str
    role: Role


class ArtifactContract(ContractModel):
    id: str
    contract_id: str
    organization_id: str
    kind: ArtifactKind
    media_type: str
    byte_size: int = Field(ge=0)
    sha256: str = Field(pattern='^[a-f0-9]{64}$')
    version: int = Field(ge=1)
    submitted: bool = False


class TypedField(ContractModel):
    name: str
    field_type: FieldType
    value: Any
    source: VersionReference
    confidence: float | None = Field(default=None, ge=0, le=1)


class EntityContract(ContractModel):
    id: str
    entity_type: EntityType
    version: int = Field(ge=1)
    fields: list[TypedField]


class RelationContract(ContractModel):
    id: str
    relation_type: RelationType
    source: VersionReference
    target: VersionReference
    actor: ActorReference | None = None
    reason_code: ReasonCode | None = None


class IdentityDto(ContractModel):
    id: str
    display_name: str
    email: str
    organization_id: str
    organization_name: str
    role: Role


class ContractContextDto(ContractModel):
    contract_id: str
    contract_name: str
    agency_organization_id: str
    agency_organization_name: str
    ngo_organization_id: str
    ngo_organization_name: str


class RuleDefinition(ContractModel):
    code: RuleCode
    version: str
    severity: RuleSeverity
    enabled: bool
    parameters: dict[str, Any]


class RuleResult(ContractModel):
    rule_code: RuleCode
    rule_version: str
    severity: RuleSeverity
    reason_code: ReasonCode
    outcome: RuleOutcome
    normalized_input: dict[str, Any]
    message: str
    expense_key: str | None = None
    remediation: str | None = None


class ValidationRunContract(ContractModel):
    id: str
    invoice_version: VersionReference
    configuration_version: VersionReference
    engine_version: str
    input_hash: str = Field(pattern='^[a-f0-9]{64}$')
    output_hash: str = Field(pattern='^[a-f0-9]{64}$')
    results: list[RuleResult]


class ValidationRunDto(ContractModel):
    id: str
    invoice_version_id: str
    configuration_version_id: str
    engine_version: str
    normalized_inputs: dict[str, Any]
    input_hash: str = Field(pattern='^[a-f0-9]{64}$')
    output_hash: str = Field(pattern='^[a-f0-9]{64}$')
    status: str
    results: list[RuleResult]
    input_manifest_id: str | None = None
    input_manifest_hash: str | None = Field(default=None, pattern='^[a-f0-9]{64}$')


class WorkflowTransition(ContractModel):
    from_state: InvoiceLifecycle
    to_state: InvoiceLifecycle
    action: Action
    role: Role


class WorkflowContract(ContractModel):
    id: str
    version: int = Field(ge=1)
    states: list[InvoiceLifecycle]
    transitions: list[WorkflowTransition]


class ViewContract(ContractModel):
    id: str
    version: int = Field(ge=1)
    role: Role
    fields: list[str]


class TemplateContract(ContractModel):
    id: str
    version: int = Field(ge=1)
    media_type: str
    content_hash: str = Field(pattern='^[a-f0-9]{64}$')
    parameters: dict[str, Any] | None = None


class ExtractionComponentVersionContract(ContractModel):
    source_artifact: VersionReference
    raw_response_artifact: VersionReference | None = None
    provider: str
    model: str
    prompt_version: str
    parser_version: str
    schema_version: str


class ValidationInputManifestContract(ContractModel):
    schema_version: str
    engine_version: str
    normalized_inputs: dict[str, Any]
    invoice_snapshot: VersionReference
    artifacts: list[VersionReference]
    schemas: list[VersionReference]
    mappings: list[VersionReference]
    rules: list[RuleDefinition]
    workflow: WorkflowContract
    views: list[ViewContract]
    templates: list[TemplateContract]
    configuration_version: VersionReference
    extraction_components: list[ExtractionComponentVersionContract]


class PackageFileDigestContract(ContractModel):
    path: str
    sha256: str = Field(pattern='^[a-f0-9]{64}$')
    byte_size: int = Field(ge=0)


class PackageBuildInputContract(ContractModel):
    schema_version: str
    package_id: str
    invoice_snapshot: VersionReference
    attestation_id: str
    validation_run: VersionReference
    validation_input_manifest_id: str
    validation_input_manifest_hash: str = Field(pattern='^[a-f0-9]{64}$')
    configuration_version: VersionReference
    template: TemplateContract
    invoice_payload: dict[str, Any]
    validation_summary: dict[str, Any]
    claims: list[dict[str, Any]]
    evidence: list[VersionReference]


class PackageReproductionManifestContract(ContractModel):
    schema_version: str
    build_input_hash: str = Field(pattern='^[a-f0-9]{64}$')
    package_manifest_hash: str = Field(pattern='^[a-f0-9]{64}$')
    archive_sha256: str = Field(pattern='^[a-f0-9]{64}$')
    archive_byte_size: int = Field(ge=0)
    files: list[PackageFileDigestContract]
    template: TemplateContract
    validation_input_manifest_id: str
    validation_input_manifest_hash: str = Field(pattern='^[a-f0-9]{64}$')
    invoice_snapshot: VersionReference


class ConfigurationBundleContract(ContractModel):
    id: str
    version: int = Field(ge=1)
    lifecycle: ConfigurationLifecycle
    scope: dict[str, str]
    schemas: list[VersionReference]
    mappings: list[VersionReference]
    rules: list[RuleDefinition]
    workflow: WorkflowContract
    views: list[ViewContract]
    templates: list[TemplateContract]
    test_evidence: VersionReference | None = None
    approval: ActorReference | None = None
    predecessor: VersionReference | None = None
    rollback_target: VersionReference | None = None


class ConfigurationLifecycleEventDto(ContractModel):
    state: ConfigurationLifecycle
    action: Action
    actor_id: str
    actor_role: Role
    actor_organization_id: str
    rationale: str
    test_evidence_id: str | None
    approval_id: str | None
    predecessor_version_id: str | None
    successor_version_id: str | None
    rollback_target_version_id: str | None
    event_hash: str = Field(pattern='^[a-f0-9]{64}$')
    occurred_at: datetime


class GovernedConfigurationVersionDto(ContractModel):
    id: str
    version: int = Field(ge=1)
    configuration: dict[str, Any]
    state: ConfigurationLifecycle
    active: bool
    history: list[ConfigurationLifecycleEventDto]


class ConfigurationLifecycleResponseDto(ContractModel):
    versions: list[GovernedConfigurationVersionDto]


class ActiveConfigurationDto(ContractModel):
    id: str
    version: int
    activated_at: str


class EventEnvelope(ContractModel):
    event_id: str
    event_type: EventType
    schema_version: int = Field(ge=1)
    actor: ActorReference
    organization_id: str
    contract_id: str
    aggregate: VersionReference
    occurred_at: datetime
    payload: dict[str, Any]
    version_references: list[VersionReference]
    reason_code: ReasonCode | None = None
